### ISSUE TITLE
Makefile question

### ISSUE THREAD

**Issue by brwhaley** [intel-iot-devkit/meta-iot-cloud#1]
It looks like the TLS directories are hardcoded in the Makefile here:
 meta-iot-cloud/recipes-aws/aws-iot-device-sdk-embedded-c/files/Makefile

-------------------------------------------------
#TLS - openSSL
TLS_LIB_DIR = /usr/lib/
TLS_INCLUDE_DIR = -I /usr/include/openssl
-------------------------------------------------
I'm getting multiple errors like this when trying to build:

cc1: warning: include location "/usr/include/openssl" is unsafe for cross-compilation [-Wpoison-system-directories]

Is it incorrectly trying to use the host's library?  Any help would be appreciated.  

Thanks,
Ben

**Comment by srware** [comment]
Hi Ben,

Good catch. I have pushed an update today which will hopefully address this.

Those paths shouldn't be required at all so have been removed as they will trigger QA errors. Try building again and let me know if you continue to have issues.

Thanks,

Scott
