### ISSUE TITLE
Update Node-RED to latest version: v2.1.3 

### ISSUE THREAD

**Issue by mkilivan** [intel-iot-devkit/meta-iot-cloud#103]
Could you update Node-RED to the latest version, please?

**Comment by srware** [comment]
Sure, I will look to get it updated this week.

**Comment by srware** [comment]
@mkilivan , I am still working on this. For 2.X releases the HTTP Request node was migrated to a new library called 'got' which is causing some build issues I need to look into some more.

**Comment by mkilivan** [comment]
@srware Thank you for the update.

**Comment by srware** [comment]
Master has been updated to version 2.1.6.
