### ISSUE TITLE
Unable to find revision 

### ISSUE THREAD

**Issue by kripscorp** [intel-iot-devkit/meta-iot-cloud#105]
WARNING: azure-iot-sdk-c-1.3.8-r0 do_fetch: Failed to fetch URL git://github.com/Azure/azure-iot-sdk-c.git;rev=a8a71c2d120c571a2d2ab6149863c2b075e7bea9, attempting MIRRORS if available
ERROR: azure-iot-sdk-c-1.3.8-r0 do_fetch: Fetcher failure: Unable to find revision a8a71c2d120c571a2d2ab6149863c2b075e7bea9 in branch master even from upstream
ERROR: azure-iot-sdk-c-1.3.8-r0 do_fetch: Fetcher failure for URL: 'git://github.com/Azure/azure-iot-sdk-c.git;rev=a8a71c2d120c571a2d2ab6149863c2b075e7bea9'. Unable to fetch URL from any source.

**Comment by srware** [comment]
Thanks for flagging this @kripscorp. Should be fixed on the dunfell branch now and I will also update other active branches this impacts.
