### ISSUE TITLE
nodejs-native config issue under Krogoth

### ISSUE THREAD

**Issue by rk-bp** [intel-iot-devkit/meta-iot-cloud#13]
I encountered this configuration error IRT nodejs-native when building meta-iot-cloud under Krogoth.

ERROR: nodejs-native-6.10.3-r0 do_configure: Function failed: do_configure (log file is located at /home/rob/rpi/build/tmp/work/x86_64-linux/nodejs-native/6.10.3-r0/temp/log.do_configure.31856)
ERROR: Logfile of failure stored in: /home/rob/rpi/build/tmp/work/x86_64-linux/nodejs-native/6.10.3-r0/temp/log.do_configure.31856
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| Usage: configure [options]
| 
| configure: error: no such option: --disable-static
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/rob/rpi/build/tmp/work/x86_64-linux/nodejs-native/6.10.3-r0/temp/log.do_configure.31856)
ERROR: Task 3084 (virtual:native:/home/rob/poky-krogoth/meta-iot-cloud/recipes-devtools/nodejs/nodejs_6.10.3.bb, do_configure) failed with exit code '1'

**Comment by srware** [comment]
Thanks for reporting.

It should be fixed now.
