### ISSUE TITLE
bitbake fetch failure https://github.com/derekbekoe/azure-multiapi-storage-python no longer exists

### ISSUE THREAD

**Issue by rk-bp** [intel-iot-devkit/meta-iot-cloud#14]
bitbake fetch failure https://github.com/derekbekoe/azure-multiapi-storage-python no longer exists

**Comment by srware** [comment]
Thanks for reporting.

Fixed: [https://github.com/intel-iot-devkit/meta-iot-cloud/commit/eade828414f3f28a576012710975c07672daec54](url)
