### ISSUE TITLE
Azure-c-shared-utility patching fails

### ISSUE THREAD

**Issue by Troels51** [intel-iot-devkit/meta-iot-cloud#171]
When building azure-c-shared-utility I get the following error

```
BBHandledException("Applying '0002-Use-pkg-config-to-find-libs.patch' failed:
stdout: checking file CMakeLists.txt
Hunk #1 succeeded at 116 with fuzz 2 (offset -10 lines).
Hunk #2 FAILED at 140.
Hunk #3 FAILED at 547.
Hunk #4 succeeded at 575 (offset -31 lines).
2 out of 4 hunks FAILED
checking file configs/azure_iot_build_rules.cmake
Hunk #1 succeeded at 76 with fuzz 2 (offset -1 lines).

stderr: ")
```
It looks like these patches were not updated when the packages git revision was updated.

**Comment by srware** [comment]
Hi @Troels51 ,

I can't reproduce this from the master branch so I could use some more information to replicate on my side. Which branch are you using?

**Comment by Troels51** [comment]
I am upgrading to scarthgap, but it looks to me that the recipe is the same on master

**Comment by srware** [comment]
I have just done a clean scarthgap build and the 'azure-c-shared-utility' recipe built without issue. Is there a possibility you have a workspace or some other source pollution in your build environment? Perhaps you can try 'bitbake -c cleanall azure-c-shared-utility' or try a clean build?

**Comment by Troels51** [comment]
I did a clean build, where I removed the build folder and it didn't help. It fetched the source but failed at patching again. Could it be a problem with my git version?

**Comment by srware** [comment]
It could be given I haven't had any similar reports about this issue.

For reference I tend to build using a [crops/poky](https://hub.docker.com/r/crops/poky) container to remove any potential OS package issues or compatibility problems. Git version in this image is 2.34.1

**Comment by Troels51** [comment]
It's the same git version that i am running. Ill keep debugging

**Comment by Troels51** [comment]
Sorry. Looks like i had a recipe that was overwriting the git hash. Don't know why i didnt catch that sooner

**Comment by srware** [comment]
No need to apologise. Glad you got it sorted.
