### ISSUE TITLE
Follow Yocto Project stable branch maintenance policies

### ISSUE THREAD

**Issue by firecrypt** [intel-iot-devkit/meta-iot-cloud#18]
Typically, meta layers follow the branch scheme of poky/oe-core so that all layers are tested against the same release. See the branch maintenance policies [here](https://wiki.yoctoproject.org/wiki/Stable_branch_maintenance).

**Comment by srware** [comment]
Good suggestion. 

I had tried to avoid this up to now due to the maintenance overhead but will start working on it as I know it's useful for people to use a branch where versions and functionality remain unchanged.

**Comment by firecrypt** [comment]
Awesome, thanks!

**Comment by srware** [comment]
The work on this is largely done. I plan to get master cleaned up and a 2.4 branch sorted soon but 2.3 back to 1.8 are finished.

Regards.
