### ISSUE TITLE
python-azure-storage error

### ISSUE THREAD

**Issue by brwhaley** [intel-iot-devkit/meta-iot-cloud#2]
I've run into another error.  It looked like there might be an issue with nspkg and storage trying to install the same files.  Any help is appreciated!  -Ben

ERROR: The recipe python-azure-storage is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
   /home/-/-/-/tmp/sysroots/edison/usr/lib/python2.7/site-packages/azure/__init__.py
 Matched in manifest-edison-python-azure-nspkg.populate_sysroot
 /home/-/-/-/tmp/sysroots/edison/usr/lib/python2.7/site-packages/azure/__init__.pyc
 Matched in manifest-edison-python-azure-nspkg.populate_sysroot
Please verify which recipe should provide the above files.

**Comment by srware** [comment]
Hi Ben,

Thanks for reporting. Strange that I have never run into this but after looking at the recipe the files it installs for one of the packages does conflict with nspkg.

Should be fixed now.
