### ISSUE TITLE
Recipe for azure-c-shared-utility points to non-existent branch 'release_2018_02_09'

### ISSUE THREAD

**Issue by ChadMcQuillen** [intel-iot-devkit/meta-iot-cloud#21]
The offending commit is '23b2acb4f54f7331586c14cc432cb82cd0eaccf1'.  The SRCREV of '4fe03ef78499f8acb1b2f8526b6cea8c432140d8' as specified in a later commit exists, but the branch does not.

**Comment by srware** [comment]
Thanks for reporting @ChadMcQuillen 

Should now be fixed :)
