### ISSUE TITLE
iotedgectl for azure

### ISSUE THREAD

**Issue by mihaelaapetroaie** [intel-iot-devkit/meta-iot-cloud#23]
Hello, 

I am new to Azure. I built the packagegroup-cloud-azure using your layer, but the command line tool iotedgeclt for Azure IoT edge does not seem to be installed. Maybe there is something I've done wrong and it is supposed to be there? 

If the layer does not include that command line tool, is there a way of using the Azure Edge without it?

Thank you,
Mihaela

**Comment by srware** [comment]
Hi @mihaelaapetroaie,

The 'iotedgectl' tool is only for v2 of Azure IoT Edge which uses Docker containerisation for managing modules etc... This is currently in public preview and not open-source so we don't yet have recipes to support it or any of the associated Python tools.

Currently we only have recipes for v1 of Azure IoT Edge [See here](https://github.com/Azure/iot-edge/tree/master/v1).

Thanks.
