### ISSUE TITLE
aws-iot-device-sdk-embedded-C version?

### ISSUE THREAD

**Issue by brwhaley** [intel-iot-devkit/meta-iot-cloud#3]
Are there plans to update meta-iot-cloud to use the 2.x version of the AWS embedded c sdk?  Thanks.

**Comment by srware** [comment]
Hi,

Amazon stopped putting out OpenSSL builds of the embedded C SDK starting with version 2.x deciding to make it more focused on low power devices (mbed etc...). For platforms running full-fat Linux with OpenSSL or equivalent there is now a C++ SDK: https://github.com/aws/aws-iot-device-sdk-cpp

I will be adding support for the new C++ SDK shortly but the embedded C SDK will likely be staying at 1.x unless there is a specific need to port 2.x to OpenSSL which isn't satisfied by the C++ SDK..

Scott

**Comment by brwhaley** [comment]
I wasn't aware of the C++ SDK but will take a look.  Thank you!

Ben
