### ISSUE TITLE
aws-iot-device-sdk-cpp: do_package_qa errors

### ISSUE THREAD

**Issue by brwhaley** [intel-iot-devkit/meta-iot-cloud#4]
Hello,

Thank you for adding the new recipe!  I'm able to compile, but am getting several errors during the package qa step of this nature:

QA Issue: non debug package contains .debug directory

Any help would be appreciated.

Thanks,
Ben

**Comment by scooter1556** [comment]
Hi Ben,

Thanks for reporting. I was building on newer versions which are smart enough to automatically add the debug folders to the debug package. I've just noticed on 2.0 (Jethro) it doesn't and throws a bunch of errors.

I will update the recipe tomorrow to get that fixed.

Scott

**Comment by brwhaley** [comment]
Thanks for all your help!

Ben

**Comment by srware** [comment]
Hi Ben,

No problem. The issue should now be fixed :)

I haven't had time to test the C++ SDK extensively so feel free to contact me if there are any issues with the libs/binaries the recipe creates.

Scott
