### ISSUE TITLE
error while compiling samples of azure-iot-sak-c in rocko branch

### ISSUE THREAD

**Issue by vsivanagulu** [intel-iot-devkit/meta-iot-cloud#43]
i have just removed the -Dskip_samples:BOOL=OFF in azure-iot-sdk.inc file. and try to compile. then i got below error. is this yocto eroor?
> t-sdk-c/1.1.32-r0/git/serializer/samples/simplesample_amqp/simplesample_amqp.c
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_get_link_name'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_clone'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_set_message_annotations'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_map_pair_count'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_open'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_set_attach_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_get_correlation_id'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_get_peer_max_message_size'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `session_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messaging_delivery_rejected'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_body_type'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `cbs_open_async'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_set_idle_timeout'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_application_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `saslmssbcbs_get_interface'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_string'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messaging_create_source'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_get_content_type'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messaging_delivery_accepted'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_symbol'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_type'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_null'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_map'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagesender_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_ulong'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_set_map_value'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `cbs_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_application_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_get_message_id'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_uuid'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagesender_send_async'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_long'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_encode'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_body_amqp_data_count'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_encoded_size'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_string'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_set_message_id'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_get_received_message_id'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_set_remote_idle_timeout_empty_frame_send_ratio'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `cbs_put_token_async'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_message_annotations'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_int'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `saslmechanism_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `session_set_incoming_window'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagesender_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagesender_open'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_set_max_message_size'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_int'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_message_annotations'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_symbol'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_send_message_disposition'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `saslclientio_get_interface_description'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_set_application_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_close'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_uuid'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_map_key_value_pair'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_create2'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `session_set_outgoing_window'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_dowork'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_add_body_amqp_data'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_set_content_type'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_set_properties'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `connection_set_trace'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `saslmechanism_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `session_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messagereceiver_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_map_value'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_set_correlation_id'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_create_data'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_set_message_format'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messaging_delivery_released'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_destroy'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `cbs_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `amqpvalue_get_inplace_described_value'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `messaging_create_target'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_get_content_encoding'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_set_content_encoding'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `properties_create'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `link_set_rcv_settle_mode'
> | ../../libiothub_client_amqp_transport.so: undefined reference to `message_get_body_amqp_data_in_place'
> | collect2: error: ld returned 1 exit status
> | iothub_client/samples/iothub_client_sample_device_twin/CMakeFiles/iothub_client_sample_device_twin.dir/build.make:107: recipe for target 'iothub_client/samples/iothub_client_sample_device_twin/iothub_client_sample_device_twin' failed
> | make[2]: *** [iothub_client/samples/iothub_client_sample_device_twin/iothub_client_sample_device_twin] Error 1
> 

I found below line in above error log
**collect2: error: ld returned 1 exit status**

**Comment by srware** [comment]
Hi @vsivanagulu,

This is semi-expected because the samples don't support building against shared libraries so the samples are linking against libs which don't exist. It's a bug with the SDK build system where the flag "build_as_dynamic" isn't taken into account for samples. I never bothered to patch it for the recipe because most of the samples require code changes like setting of the connection string to be useful. Compiling them as part of the SDK recipe is of very limited use.

I may add an example recipe showing how one of the samples could be compiled in the correct manner separate from the SDK build. Hopefully I will get time in the near future to do so.

**Comment by vsivanagulu** [comment]
@srware  thats great work. Please post that example recipe. Also I have time now to do that Guide me to write that sample recipe. I would really very happy to work and support for "meta-iot-cloud" team.
Note: I have compiled libs succesfully How can I test azure-iot-sdk-c without samples. is there any other way.

**Comment by srware** [comment]
I have added an example showing how to compile one of the Azure IoT SDK samples in it's own recipe over here: [meta-iot-cloud-examples](https://github.com/srware/meta-iot-cloud-examples)

The example code is taken straight from the SDK repository with a slightly modified cmake build script. Something similar should work to build your own code or other samples against the meta-iot-cloud recipes.

In terms of testing the idea here is that you would already have known working code which depends on the Azure IoT SDK. For instance, I create an application on my Ubuntu dev machine which requires the Azure IoT SDK, I then want to add this to my Yocto image so I create a recipe for my code which depends on azure-iot-sdk-c provided by this layer.
