### ISSUE TITLE
Not able to see Sensors in Node RED

### ISSUE THREAD

**Issue by SatinderSidhu** [intel-iot-devkit/meta-iot-cloud#46]
I am developer, got the intel grove kit from one of the session attended lately. I am have started a  lab at home but hitting a road blocker. I have connected everything, but not able to detect the sensors in dashboard, so can't run any program. Is there troubleshooting i can do?

**Comment by SatinderSidhu** [comment]
![image](https://user-images.githubusercontent.com/7516751/55675320-cf6ae400-588e-11e9-8fbd-0a2793afb5c7.png)

![image](https://user-images.githubusercontent.com/7516751/55675321-d4c82e80-588e-11e9-867b-c858443fa1b9.png)

**Comment by SatinderSidhu** [comment]
![image](https://user-images.githubusercontent.com/7516751/55675373-95e6a880-588f-11e9-9f42-121db0c5f21c.png)

**Comment by srware** [comment]
Hi @SatinderSidhu,

This repository isn't connected to the developer kit you are inquiring about so I am going to close this.

You should ask the question in the Intel forums.

Thanks
