### ISSUE TITLE
Issues with dev and dbg packages of aws-iot-device-sdk-cpp

### ISSUE THREAD

**Issue by brwhaley** [intel-iot-devkit/meta-iot-cloud#5]
Hello,

The standard package seems build correctly for me.  However, I get the error below when building an image with the -dev package:

 satisfy_dependencies_for: Cannot satisfy the following dependencies for aws-iot-device-sdk-cpp-dev:
       rapidjson (= 1.1.0-r0) 
 opkg_install_cmd: Cannot install package aws-iot-device-sdk-cpp-dev.

Additionally, the -dbg package built without errors but did not seem to include the header files in the image.  Should those be included with the -dbg package?

Thanks again for your help.

-Ben

**Comment by srware** [comment]
Hi Ben,

The issue you mentioned regarding rapidjson should now be fixed when building a full image.

Regarding header files, they are always included with the -dev package, not the -dbg package.

Regards.
