### ISSUE TITLE
Question: Version of azure-iot-sdk-c

### ISSUE THREAD

**Issue by DasRoteSkelett** [intel-iot-devkit/meta-iot-cloud#50]
Hi! 
I am a complete noob when it comes to the azure-iot-sdk-c, I was just wondering, if there is any particular reason that the current version is at 1.2.10 and not 1.3.x or anywhere closer like 1.2.14? And if there are no particular reasons, would you accept a PR?

Regards,

   Matthias

**Comment by srware** [comment]
Hi Matthias,

The only reason is time. I maintain this layer on a best effort basis so generally when someone asks for an update or I have a particular need myself. I will happily accept a PR on the master branch or a request to update a given recipe. 

Many thanks.
