### ISSUE TITLE
Update azure-iot-sdk-c to last version (1.3.8)?

### ISSUE THREAD

**Issue by bpastore** [intel-iot-devkit/meta-iot-cloud#66]
Hello,
I'm working on the design of a new IoT device based on Linux (Yockto).
I want use the last Azure SDK but I'm a newbie on receipe world.
Where can I start? someone can help me?
Thanks in advace
 
Best regards

**Comment by srware** [comment]
@bpastore, I will try to find some time to update in the coming days. This particular SDK requires a lot of work to update due to the many dependencies it has so it is update infrequently at best.

**Comment by scooter1556** [comment]
@bpastore, master branch has been updated.

Let me know if there are any problems.

**Comment by srware** [comment]
@bpastore , master has branch has been updated.

Let me know if there are any problems.
